name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Initial Server Setup
        # if: steps.check_setup.outputs.needs_setup == 'true'
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            if [ ! -f /home/${{ secrets.SSH_USERNAME }}/.setup_done ]; then
              echo "⭐️ SSH 키 생성 및 GitHub에 등록"
              ssh-keygen -t rsa -b 4096 -C "dohk325@gmail.com" -f ~/.ssh/id_rsa -N ""
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)
              curl -H "Authorization: token ${{ secrets.TOKEN }}" \
                  -X POST \
                  -d "{\"title\":\"Server SSH Key\",\"key\":\"$PUBLIC_KEY\"}" \
                  https://api.github.com/user/keys

              echo "⭐️ Astronomer 설치 및 Airflow 시작"
              curl -sSL install.astronomer.io | sudo bash -s -- v1.25.0 
              git clone git@github.com:TEDD325/airflow-dev.git
              cd airflow-dev
              astro dev start &
              sleep 300
              pkill astro

              echo "⭐️ 설정 완료"
              touch /home/${{ secrets.SSH_USERNAME }}/.setup_done
            else
              echo "⭐️ Already Initialized"
            fi

  deployment:
    runs-on: ubuntu-latest
    needs: integration  # integration job이 완료된 후 실행

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd ${{ github.repository.name }}
            git pull origin main
            echo "⭐️ 배포 완료"
            # 추가적인 배포 명령어들
